### ISSUE TITLE
ImportError: cannot import name 'post_syncdb', Py3, Django 1.9

### ISSUE THREAD

**Issue by Snpefk** [liberation/django-elasticsearch#39]
Hi, I'm trying to use your wrapper (branch with support Django 1.9) and got the error. 
`ImportError:` cannot import name 'post_syncdb'`

I'm using Elastisearch 2.2.0, Django 1.9.2 and Python 3.5.1.

**Comment by Snpefk** [comment]
Oh nevermind. That was my mistake. Work fine with Django 1.9 and Python 3

**Comment by lauxley** [comment]
Note that Elasticsearch 2 is not officially supported (some features won't work) and i'm very confused at how you made it work with python 3 ?

**Comment by Snpefk** [comment]
Yeah, I was a bit hasty, got the error `TypeError: es_syncdb_callback() missing 2 required positional arguments: 'app' and 'created_models'` when migrate models.
